// Generated by CoffeeScript 1.10.0
var assert;

assert = chai.assert;

describe('AppView', function() {
  var appView;
  appView = null;
  beforeEach(function() {
    return appView = new AppView({
      model: new App()
    });
  });
  return describe('stand', function() {
    return it('should disable player controls', function() {
      appView.$el.find('.stand-button').click();
      assert.strictEqual(appView.$el.find('.hit-button').attr('disabled'), 'disabled');
      return assert.strictEqual(appView.$el.find('.stand-button').attr('disabled'), 'disabled');
    });
  });
});
